### ISSUE TITLE
Error with Jars

### ISSUE THREAD

**Issue by SteZhyv** [Sominemo/monobank_api#1]
While I try to make request, this error will appear:

`Unhandled Exception: RangeError (start): Invalid value: Only valid value is 0: 4
RangeError.checkValidRange (dart:core/errors.dart:360:7)
_StringBase.substring (dart:core-patch/string_patch.dart:398:27)
new Jar._fromJson (package:monobank_api/src/mono.dart:430:38)
new Client._fromJson.<anonymous closure> (package:monobank_api/src/mono.dart:133:28)
MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
List.addAll (dart:core-patch/growable_array.dart:319:13)
new Client._fromJson (package:monobank_api/src/mono.dart:131:10)
PersonalMethods.clientInfo (package:monobank_api/src/mono.dart:977:19)
<asynchronous suspension>`

**Comment by Sominemo** [comment]
Hello, it would really help if you could set a breakpoint at `/lib/src/mono.dart:437` and hover over "data" variable to see what it looks like, as I don't have a jar that would cause such problem.

![image](https://github.com/Sominemo/monobank_api/assets/19842935/ae03cca4-4082-4dfa-9080-152b7f91c399)

In meanwhile, I released version 2.0.3 with more careful sendId handling which *may* fix the issue, but I'm still not sure if I process the input correctly without seeing your edge case.

Thank you!
